- name: Update Packages
  apt:
   update_cache: yes

- name: Install Nginx
  apt:
   name: nginx

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: True
    masked: no